baseURL = 'https://mateusmelo.xyz'
languageCode = 'en-us'
title = "Mateus Melo"
theme = 'etch'

contentDir = 'content'

[params]
  description = "Wellcome to my personal website"
  copyright = "CC BY-SA ©"
  name = "Mateus Melo"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/resume/"
    weight = 30

  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/mateusmeloxyz"
    weight = 25

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "/#contact"
    weight = 35

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = false

  [markup.tableOfContents]
    ordered = true

languageCode = "en"

# Multi-lang Settings
[languages]
  [languages.en]
    languageName = 'English'
    weight = 10
    contentDir = 'content/en'
  [languages.pt]
    title = "Mateus Melo"
    languageName = 'Português'
    weight = 20
    contentDir = 'content/pt'